services:
  # Adminer 
  adminer:
    image: adminer:latest
    container_name: monitoring-adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha
    networks:
      - backend-network
    depends_on:
      - postgres
    restart: unless-stopped

  # Redis Commander 
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: monitoring-redis-commander
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - backend-network
    depends_on:
      - redis
    restart: unless-stopped