services:
  postgres:
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"

  backend:
    build:
      dockerfile: Dpckerfile.dev
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      DEBUG: "true"
      LOG_LEVEL: debug
    
  frontend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"

volumes:
  backend_node_modules:
  frontend_node_modules: