global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'api-monitoring-platform'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  #node exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
  #postgress sql
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
  
  #Redis
  - job_name: 'redis'
    static_configs: 
      - targets: ['redis-exporter:9121']
  
  # BAckend API
  - job_name: 'backend-api'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/metrics'